#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
MPI_WRAPPER=mvapich2

export CC=mpicc
export CXX=mpicxx
#export MV2_ENABLE_AFFINITY=0
#export MV2_VBUF_POOL_SIZE=8192
#export MV2_VBUF_SECONDARY_POOL_SIZE=1024
#export MV2_VBUF_TOTAL_SIZE=24k

export INTEL_LICENSE_FILE=/share/apps/Intel/licenses/Licenses-2014.0513
export PATH=/share/apps/cmake/cmake-2.8.9/gcc-4.4.6/bin:/share/apps/hwloc/1.7.1-intel.13.1.1/bin:/share/apps/mvapich2/1.9//bin:/share/apps/gnu/gcc/4.7.3/bin:/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/linux-x64:/users/c705234/bin:/share/apps/Intel/compiler/13.1.1/bin
export LD_LIBRARY_PATH=/share/apps/hwloc/1.7.1-intel.13.1.1/lib:/share/apps/mvapich2/1.9//lib:/share/apps/gnu/gmp/5.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpfr/3.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpc/1.0.1/gcc/4.4.6/lib:/share/apps/gnu/gcc/4.7.3/lib64:/opt/gridengine/lib/linux-x64:/opt/gridengine/lib/linux-x64:/share/apps/boost/1.53/gcc/4.4.6/lib:/share/apps/Intel/compiler/13.1.1/lib/intel64:/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64:/share/apps/Intel/compiler/13.1.1/ipp/lib/intel64:/share/apps/Intel/compiler/13.1.1/tbb/lib/intel64

## common ##
COMMON_CMAKE_CXX_FLAGS="-O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_C_COMPILER=mpicc
COMMON_CMAKE_CXX_COMPILER=mpicxx
COMMON_MPI_CXX_FOUND=FALSE
COMMON_AMBIENT_THREADING="cilk"
COMMON_AMBIENT_PARALLEL_MKL=ON # only needed because selector=manual
COMMON_BLAS_LAPACK_SELECTOR="manual" # TODO: mkl_parallel should work as well
COMMON_MAQUISLapack_LIBRARIES="-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm"
COMMON_MAQUISLapack_LIB_DIRS=/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64
COMMON_MAQUISLapack_INCLUDE_DIRS=/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64
COMMON_PLASMA_LIBRARIES="-lplasma -lcoreblas -lcblas -llapacke -lquark"
COMMON_PLASMA_LIB_DIR="/share/apps/plasma/2.5.0/icc/13.1.1/lib"
COMMON_CMAKE_INSTALL_PREFIX=~/opt/dmrg
COMMON_CMAKE_BUILD_WITH_INSTALL_RPATH=ON
COMMON_CMAKE_INSTALL_RPATH_USE_LINK_PATH=ON
## ambient ##
AMBIENT_BOOST_BINDINGS_INCLUDE=/share/apps/alps/r6979/icc/13.1.1-nompi/include/boost
AMBIENT_SCALAPACK_LIBRARY="-lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64"
AMBIENT_ENABLE_REGRESSION_PERFORMANCE=OFF
AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=OFF
## dmrg ##
DMRG_CMAKE_CXX_FLAGS_RELEASE="$COMMON_CMAKE_CXX_FLAGS"
DMRG_ALPS_ROOT_DIR=/share/apps/alps/r6979/icc/13.1.1-nompi
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

DMRG_REGRESSION_UNIT_TESTING=OFF
DMRG_REGRESSION_APPLICATION_TESTS=OFF
DMRG_REGRESSION_PERFORMANCE_TESTS=ON


source $ROOT_DIR/scripts/common/common.sh 
execute $*
