#!/bin/bash
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=ambient
COMPILER=intel
MPI_WRAPPER=mvapich2

export MKLROOT=/share/apps/Intel/compiler/13.1.1/mkl
export PLASMA_ROOT=/share/apps/plasma/2.5.0/icc/13.1.1
export ALPS_ROOT=/share/apps/alps/r6979/icc/13.1.1-nompi
export CXX=mpicxx
export CC=mpicc

export INTEL_LICENSE_FILE=/share/apps/Intel/licenses/Licenses-2014.0513
export PATH=/share/apps/cmake/cmake-2.8.9/gcc-4.4.6/bin:/share/apps/hwloc/1.7.1-intel.13.1.1/bin:/share/apps/mvapich2/1.9//bin:/share/apps/gnu/gcc/4.7.3/bin:/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/linux-x64:/users/c705234/bin:/share/apps/Intel/compiler/13.1.1/bin
export LD_LIBRARY_PATH=/share/apps/hwloc/1.7.1-intel.13.1.1/lib:/share/apps/mvapich2/1.9//lib:/share/apps/gnu/gmp/5.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpfr/3.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpc/1.0.1/gcc/4.4.6/lib:/share/apps/gnu/gcc/4.7.3/lib64:/opt/gridengine/lib/linux-x64:/opt/gridengine/lib/linux-x64:/share/apps/boost/1.53/gcc/4.4.6/lib:/share/apps/Intel/compiler/13.1.1/lib/intel64:/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64:/share/apps/Intel/compiler/13.1.1/ipp/lib/intel64:/share/apps/Intel/compiler/13.1.1/tbb/lib/intel64

COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
COMMON_CMAKE_INSTALL_PREFIX=~/opt/dmrg
COMMON_CMAKE_BUILD_WITH_INSTALL_RPATH=ON
COMMON_CMAKE_INSTALL_RPATH_USE_LINK_PATH=ON
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
