#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=standard
COMPILER=intel
MPI_WRAPPER=shared

export CXX=icpc
export CC=icc
module load boost/1.53
module load gcc/4.7.2
module load intel-compiler/13.1.1
module load openmpi/1.6.4/icc/13.1.1
module load cmake/2.8.9

## common ##
COMMON_ENABLE_OMP=ON
COMMON_CMAKE_CXX_FLAGS="-std=c++11 -O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_CXX_FLAGS_RELEASE="-std=c++11 -O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_C_COMPILER=icc
COMMON_CMAKE_CXX_COMPILER=icpc
## ambient ##
AMBIENT_BOOST_BINDINGS_INCLUDE=/share/apps/alps/r6979/icc/13.1.1/include/boost
AMBIENT_SCALAPACK_LIBRARY="-lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64"
## dmrg ##
DMRG_DEFAULT_BLAS_LAPACK=manual
DMRG_CMAKE_CXX_FLAGS_RELEASE="$COMMON_CMAKE_CXX_FLAGS"
DMRG_BLAS_LAPACK_MANUAL_LIBS="-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_lapack95_lp64 -lpthread $AMBIENT_PLASMA_LIBRARY"
DMRG_BLAS_LAPACK_MANUAL_LIBS_DIR=/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64
DMRG_BLAS_LAPACK_MANUAL_INCLUDES=/share/apps/Intel/compiler/13.1.1/mkl/include
DMRG_ALPS_ROOT_DIR=/share/apps/alps/r6979/icc/13.1.1
DMRG_USE_AMBIENT=OFF

source $ROOT_DIR/scripts/common/common.sh 
execute $*
