#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=omp
COMPILER=intel

ALPS_DIR=/share/apps/alps/r6979/icc/13.1.1-nompi
MAQUIS_INSTALL=~/opt/dmrg
echo $MAQUIS_INSTALL

export ALPS_ROOT=${ALPS_DIR}
export INTEL_LICENSE_FILE=/share/apps/Intel/licenses/Licenses-2014.0513
export PATH=/share/apps/cmake/cmake-2.8.9/gcc-4.4.6/bin:/share/apps/hwloc/1.7.1-intel.13.1.1/bin:/share/apps/mvapich2/1.9//bin:/share/apps/gnu/gcc/4.7.3/bin:/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/users/c705234/maquis2014/src/scripts/common:/users/c705234/mptoolkit/install/bin:/users/c705234/bin:/share/apps/bin::/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/gridengine/bin/linux-x64:/users/c705234/bin:/share/apps/Intel/compiler/13.1.1/bin
export LD_LIBRARY_PATH=/share/apps/hwloc/1.7.1-intel.13.1.1/lib:/share/apps/mvapich2/1.9//lib:/share/apps/gnu/gmp/5.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpfr/3.1.2/gcc/4.4.6/lib:/share/apps/gnu/mpc/1.0.1/gcc/4.4.6/lib:/share/apps/gnu/gcc/4.7.3/lib64:/opt/gridengine/lib/linux-x64:/opt/gridengine/lib/linux-x64:/share/apps/boost/1.53/gcc/4.4.6/lib:/share/apps/Intel/compiler/13.1.1/lib/intel64:/share/apps/Intel/compiler/13.1.1/mkl/lib/intel64:/share/apps/Intel/compiler/13.1.1/ipp/lib/intel64:/share/apps/Intel/compiler/13.1.1/tbb/lib/intel64
export MKLROOT=/share/apps/Intel/compiler/13.1.1/mkl
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}
export CC=icc
export CXX=icpc

COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"

DMRG_ENABLE_OMP=ON
DMRG_USE_AMBIENT=OFF
DMRG_REGRESSION_PERFORMANCE_TESTS=OFF

source $ROOT_DIR/scripts/common/common.sh 
execute $*
