#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="configure"
# end of target states #
PREFIX=ambient
COMPILER=gcc
COMPILER_VERSION=4.7.3
MYAPPS=/project/h07/dolfim/apps/daint/gcc_4_7_3

export ALPS_ROOT=$MYAPPS/alps
export PLASMA_ROOT=$MYAPPS/plasma
export PATH=${ALPS_ROOT}/bin:${PATH}

module load PrgEnv-gnu
module load cray-hdf5
module load cmake

COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
