#!/bin/bash
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=13.1
MYAPPS=/scratch/daint/dolfim/apps/intel_13_1_3

MAQUIS_INSTALL=$MYAPPS/maquis/$CONFIG_NAME
echo $MAQUIS_INSTALL


if [[ -z "$MAQUIS_ONCE" ]]
then
    export MAQUIS_ONCE=true
    module load gcc/4.7.3
    module switch PrgEnv-cray PrgEnv-intel
    module load intel/13.1.3.192
    module load cray-hdf5/1.8.11
    module load cmake

    export PLASMA_ROOT=$MYAPPS/plasma
    export ALPS_ROOT=$MYAPPS/alps-cxx11
    export CRAYPE_LINK_TYPE=dynamic
    export PATH=$ALPS_ROOT/bin:$MYAPPS/hdf5/bin:$MYAPPS/bin:$PATH
    export LD_LIBRARY_PATH=${ALPS_ROOT}/lib:$MYAPPS/hdf5/lib:${LD_LIBRARY_PATH}
    export CXX=CC.dynamic # CC -dynamic -lz $*
    export CC=cc.dynamic  # cc -dynamic -lz $*
    
    export PATH=${MAQUIS_INSTALL}/bin:${PATH}
fi

COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
