#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="configure"
# end of target states #
PREFIX=ambient_thread
COMPILER=intel
COMPILER_VERSION=13.1
MPI_WRAPPER=cray # md: I think it's mvapich2
MPI_WRAPPER_VERSION=""
MYAPPS=/project/h07/dolfim/apps/daint/intel_13_1_0
ALPS_DIR=$MYAPPS/alps

export ALPS_ROOT=${ALPS_DIR}
export PATH=${ALPS_DIR}/bin:${PATH}
#export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH} # md: ALPS is installed without python, therefore not needed

export XTPE_LINK_TYPE=dynamic

module load gcc/4.7.3
module load PrgEnv-intel
module load cray-hdf5
module load cmake
#module load perftools

## common ##
COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_CMAKE_C_COMPILER="cc"
COMMON_CMAKE_CXX_COMPILER="CC"
COMMON_CMAKE_CXX_FLAGS="-Wfatal-errors -w -O3 -DNDEBUG"
COMMON_CMAKE_CXX_FLAGS_RELEASE=${MAQUIS_COMMON_CMAKE_CXX_FLAGS}
COMMON_AMBIENT_THREADING="cilk"
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$MYAPPS/plasma/lib"
## dmrg ##
DMRG_ALPS_ROOT_DIR=$ALPS_ROOT
DMRG_ENABLE_OMP=OFF
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON
DMRG_REGRESSION_PERFORMANCE_TESTS=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
