#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=13.1
MYAPPS=/project/h07/dolfim/apps/daint/intel_13_1_0

export PLASMA_ROOT=$MYAPPS/plasma
export ALPS_ROOT=$MYAPPS/alps
export CRAYPE_LINK_TYPE=dynamic
export CXX=CC.dynamic # CC -dynamic -lz $*
export CC=cc.dynamic  # cc -dynamic -lz $*

if [[ -z "$MAQUIS_ONCE" ]]
then
    export MAQUIS_ONCE=true
    module load gcc/4.7.3
    module switch PrgEnv-cray PrgEnv-intel
    module load intel/13.1.3.192
    module load cray-hdf5/1.8.11
    module load cmake
fi

COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
