#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=gcc
COMPILER_VERSION=4.8.1
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.9

ALPS_DIR=$HOME/apps/monch/alps-gcc481-cxx11
MAQUIS_INSTALL=$ROOT_DIR/_installs/$HOST/$CONFIG_NAME
echo "Install into $MAQUIS_INSTALL."

export ALPS_ROOT=$ALPS_DIR
export PLASMA_ROOT=$HOME/apps/monch/plasma-gcc481
export PATH=${ALPS_ROOT}/bin:${PATH}
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}
export LD_LIBRARY_PATH=${ALPS_ROOT}/lib:${PLASMA_ROOT}/lib:${LD_LIBRARY_PATH}
export CC=gcc
export CXX=g++

module load gcc/4.8.1
module load hdf5/1.8.12-gcc-4.8.1
module load mvapich2/1.9-gcc-4.8.1
module load mkl/11.1.1.106-intel14.0.1
module load python/2.7.6-gcc-4.8.1
module load cmake

# MAQUIS exports after ALPS
export PATH=${MAQUIS_INSTALL}/bin:${PATH}

# COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
COMMON_CMAKE_BUILD_TYPE="Release"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
