#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=14.0.1
MPI_WRAPPER=impi
MPI_WRAPPER_VERSION=4.1.1

MAQUIS_INSTALL=$ROOT_DIR/_installs/$HOST/$CONFIG_NAME
echo $MAQUIS_INSTALL

module load gcc/4.8.1
module load hdf5/1.8.12-intel14.0.1 
module load python/2.7.5-intel-14.0.1
module load intel/14.0.1
module load cmake

export ALPS_ROOT=$HOME/apps/monch/alps-intel-boost_1_54_0
export PATH=${ALPS_ROOT}/bin:${PATH}
export LD_LIBRARY_PATH=${ALPS_ROOT}/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${ALPS_ROOT}/lib:${PYTHONPATH}
export I_MPI_LINK=opt_mt # optimized, multithreaded version of the Intel MPI Library
export CC=mpiicc
export CXX=mpiicpc

## uncomment for profiling
#source /apps/monch/intel/impi/4.1.1.036/intel64/bin/mpivars.sh
#source $ROOT_DIR/scripts/monch/itac.sh

# MAQUIS exports after ALPS
export PATH=${MAQUIS_INSTALL}/bin:${PATH}

COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$HOME/apps/monch/plasma-intel/lib"
## dmrg ##
DMRG_ALPS_ROOT_DIR=$ALPS_ROOT
DMRG_ENABLE_OMP=OFF
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
