#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=14.0.1
MPI_WRAPPER=mvapich2 # not used
MPI_WRAPPER_VERSION=1.9

MAQUIS_INSTALL=$ROOT_DIR/_installs/monch/$CONFIG_NAME
echo $MAQUIS_INSTALL

module load gcc/4.8.1 alps/r7398/intel-14.0.1
export CC=icc
export CXX=icpc

# MAQUIS exports after ALPS
export PATH=${MAQUIS_INSTALL}/bin:${PATH}

COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}

#COMMON_CMAKE_C_COMPILER=mycc
#COMMON_CMAKE_CXX_COMPILER=myCC
#COMMON_MPI_CXX_FOUND=TRUE
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$HOME/apps/monch/plasma-intel/lib"
## dmrg ##
DMRG_ALPS_ROOT_DIR=$ALPS_ROOT
DMRG_ENABLE_OMP=OFF
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON


source $ROOT_DIR/scripts/common/common.sh 
execute $*
