SET(CTEST_PROJECT_NAME "test")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "alps.comp-phys.org")
  SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=HP2C+-+MAQUIS")
  SET(CTEST_PROJECT_SUBPROJECTS VLI)
  SET(CTEST_DROP_SITE_CDASH TRUE)
# SET(CTEST_TRIGGER_SITE "")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
