#!/bin/bash

time ./se_gmp/a_gmp.out $1 $1  out.gmp > out.gmp
time ./se_vli/a_vli.out $1 $1  out.vli > out.vli
time ./se_vli_omp/a_vli_omp.out $1 $1  out.omp > out.omp
time ./se_vli_mix/a_vli_mix.out $1 $1  out.mix > out.mix
