#!/bin/bash

PATH_TRUNK=~/MAQUIS/trunk/src
PATH_TEST_KERNELS=~/MAQUIS/trunk/src/types/build_mvapich2
PATH_PDMRG=~/MAQUIS/trunk/src/dmrg/build_mvapich2/regression/pdmrg
#go in test directory
cd $PATH_TEST_KERNELS
#compile test
make clean
echo "-----------------------------------"
echo " Compile Ambient and kernel tests  "
echo "-----------------------------------"

make -j 
echo "-----------------------------------"
echo " Ambient tests are not implemented "
echo "-----------------------------------"

echo "-----------------------------------"
echo "         run kernels tests         "
echo "-----------------------------------"
#run test
make test

cd $PATH_PDMRG
echo "-----------------------------------"
echo "           Compile pdmrg           "
echo "-----------------------------------"
make 
echo "-----------------------------------"
echo "            run  pdmrg             "
echo "-----------------------------------"
mpirun -np 2 ./pdmrg.exec  ../../../regression/dmrg/params_ff_short ../../../regression/dmrg/model_ff_short
