#!/bin/bash

#today only two targets icc+intel_mpi, icc+mvapich2
BUILD_IMPI=build_intel_impi
BUILD_MVAPICH2=build_intel_mvapich2
BUILD_OPENMPI=build_intel_openmpi

TYPES=types/
DMRG=dmrg/
AMBIENT=ambient/

PATH_TRUNK=~/MAQUIS/trunk/src/
PATH_TEST_KERNELS=~/MAQUIS/trunk/src/types/

#compiler and boost
COMPILER=iccxe/
COMPILER_NAME=intel
VERSION_COMPILER=2011

BOOST=boost/
VERSION_BOOST=1.46.1

#intel MPI
WRAPPER_INTEL_MPI=impi/
VERSION_WRAPPER_INTEL_MPI=4.0
#mvapich2 and more later 
WRAPPER_MVAPICH2_MPI=mvapich2/
VERSION_WRAPPER_MVAPICH2_MPI=1.6-intel
#go in test directories
WRAPPER_OPENMPI_MPI=openmpi/
VERSION_WRAPPER_OPENMPI_MPI=1.5.3


module load ${COMPILER}${VERSION_COMPILER} ${BOOST}${VERSION_BOOST} ${WRAPPER_INTEL_MPI}${VERSION_WRAPPER_INTEL_MPI} ${WRAPPER_MVAPICH2_MPI}${VERSION_WRAPPER_MVAPICH2_MPI} ${WRAPPER_OPENMPI_MPI}${VERSION_WRAPPER_OPENMPI_MPI} 

for i in ${BUILD_IMPI} ${BUILD_MVAPICH2} ${BUILD_OPENMPI}
do
    cd ${PATH_TRUNK}${TYPES}${i}
    echo "--------------------------"
    echo "--Compile Ambient Tests---"
    echo "-----    "${i}     "------"
    echo "--------------------------"
    make clean
    make -j
    echo "--------------------------"
    echo "--    run tests        ---"
    echo "-----    "${i}     "------"
    echo "--------------------------"
    make test
done
