#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="configure"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=2013
MPI_WRAPPER=openmpi
MPI_WRAPPER_VERSION=1.6.3-intel
BOOST=boost
BOOST_VERSION=1.53.0
CMAKE=cmake

export CC=mpicc
export CXX=mpicxx
export BOOST_ROOT=/project/h07/BOOST_1_53/

module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load ${CMAKE}

## common ##
THREADING_FLAGS="-DAMBIENT_CILK" # -openmp -DAMBIENT_OMP
COMMON_CMAKE_CXX_FLAGS="-std=c++11 -O3 -DNDEBUG -w -Wfatal-errors $THREADING_FLAGS -L/apps/castor/plasma-2.4.6/lib"
COMMON_CMAKE_C_COMPILER=mpicc
COMMON_CMAKE_CXX_COMPILER=mpicxx
COMMON_MPI_CXX_FOUND=FALSE
## ambient ##
AMBIENT_BOOST_BINDINGS_INCLUDE=/project/h07/TEST_ALPS/include
AMBIENT_SCALAPACK_LIBRARY="-lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64"
AMBIENT_PLASMA_LIBRARY="-lplasma -lcoreblas -lcblas -llapacke -lquark"
AMBIENT_ENABLE_REGRESSION_PERFORMANCE=ON
AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=ON
## dmrg ##
DMRG_DEFAULT_BLAS_LAPACK=manual
DMRG_CMAKE_CXX_FLAGS_RELEASE="$COMMON_CMAKE_CXX_FLAGS"
DMRG_BLAS_LAPACK_MANUAL_LIBS="-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_lapack95_lp64 -lpthread $AMBIENT_PLASMA_LIBRARY"
DMRG_BLAS_LAPACK_MANUAL_LIBS_DIR=/apps/castor/intel/mkl/lib/intel64
DMRG_BLAS_LAPACK_MANUAL_INCLUDES=/apps/castor/intel/mkl/include
DMRG_ALPS_ROOT_DIR=/project/h07/TEST_ALPS
DMRG_BUILD_REGRESSION=OFF 
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
