#!/bin/bash -l
STATE="void"
STATE_AMBIENT="build"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=gcc
COMPILER_VERSION=4.8.1
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.9-gcc-4.8.1

export MKLROOT=/apps/castor/intel-2013/mkl
export PLASMA_ROOT=/apps/castor/plasma-2.4.6
export ALPS_ROOT=/project/h07/TEST_ALPS
export CXX=mpicxx
export CC=mpicc

export MV2_ENABLE_AFFINITY=0
export MV2_VBUF_POOL_SIZE=8192
export MV2_VBUF_SECONDARY_POOL_SIZE=1024
export MV2_VBUF_TOTAL_SIZE=24k

module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load hdf5/1.8.9-gcc
module load cmake

COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
COMMON_PLASMA_LIBRARIES="-lplasma -lcoreblas -llapacke -lquark /apps/castor/intel-2013/compiler/lib/intel64/libimf.a /apps/castor/intel-2013/compiler/lib/intel64/libirc.a"
AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=ON
AMBIENT_ENABLE_REGRESSION_PERFORMANCE=ON
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
