#!/bin/bash
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=2013
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.9-intel-wocuda

export MKLROOT=/apps/castor/intel-2013/mkl
export PLASMA_ROOT=/apps/castor/plasma-2.4.6
export ALPS_ROOT=/users/akosenko/apps/alps/r7368/castor/icc/13.1.0
export CXX=mpicxx
export CC=mpicc

export MV2_ENABLE_AFFINITY=0
export MV2_VBUF_POOL_SIZE=8192
export MV2_VBUF_SECONDARY_POOL_SIZE=1024
export MV2_VBUF_TOTAL_SIZE=24k

source /etc/profile.d/modules.sh
module load cuda/5.5
module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load cmake

COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_PDMRG=ON
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON
DMRG_REGRESSION_PERFORMANCE_TESTS=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
