#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=standard
COMPILER=intel
COMPILER_VERSION=2013
MPI_WRAPPER=openmpi
MPI_WRAPPER_VERSION=1.6.3-intel
BOOST=boost
BOOST_VERSION=1.53.0
CMAKE=cmake

export CXX=icpc
export CC=icc
export BOOST_ROOT=/project/h07/BOOST_1_53/

module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load ${CMAKE}

## common ##
COMMON_ENABLE_OMP=ON
COMMON_CMAKE_CXX_FLAGS="-std=c++11 -O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_CXX_FLAGS_RELEASE="-std=c++11 -O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_C_COMPILER=icc
COMMON_CMAKE_CXX_COMPILER=icpc
## ambient ##
AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=OFF
AMBIENT_ENABLE_REGRESSION_PERFORMANCE=OFF
AMBIENT_BOOST_BINDINGS_INCLUDE=/project/h07/TEST_ALPS/include
AMBIENT_SCALAPACK_LIBRARY="-lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64"
## dmrg ##
DMRG_DEFAULT_BLAS_LAPACK=manual
DMRG_BLAS_LAPACK_MANUAL_LIBS="-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread"
DMRG_BLAS_LAPACK_MANUAL_LIBS_DIR=/apps/castor/intel/mkl/lib/intel64
DMRG_BLAS_LAPACK_MANUAL_INCLUDES=/apps/castor/intel/mkl/include
DMRG_ALPS_ROOT_DIR=/project/h07/TEST_ALPS
DMRG_BUILD_REGRESSION=OFF 
DMRG_USE_AMBIENT=OFF

source $ROOT_DIR/scripts/common/common.sh 
execute $*
