#!/bin/bash -l
STATE="void"
STATE_AMBIENT="build"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=2013
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.9-intel-wocuda

export BOOST_ROOT=/project/h07/BOOST_1_53
export MKLROOT=/apps/castor/intel-2013/mkl
export PLASMA_ROOT=/apps/castor/plasma-2.4.6
export ALPS_ROOT=/project/h07/TEST_ALPS
export CXX=mpicxx
export CC=mpicc

export MV2_ENABLE_AFFINITY=0
export MV2_VBUF_POOL_SIZE=8192
export MV2_VBUF_SECONDARY_POOL_SIZE=1024
export MV2_VBUF_TOTAL_SIZE=24k

module load cuda/5.0
module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load cmake

COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=ON
AMBIENT_ENABLE_REGRESSION_PERFORMANCE=ON
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
