#!/bin/bash
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=omp
COMPILER=intel
COMPILER_VERSION=2013
BOOST=boost
BOOST_VERSION=1.53.0
CMAKE=cmake

export CXX=icpc
export CC=icc
export BOOST_ROOT=/project/h07/BOOST_1_53/
export MKLROOT=/apps/castor/intel-2013/mkl

source /etc/profile.d/modules.sh
module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${CMAKE}

## common ##
COMMON_CMAKE_CXX_FLAGS="-O3 -DNDEBUG -w -Wfatal-errors"
COMMON_CMAKE_CXX_FLAGS_RELEASE=$COMMON_CMAKE_CXX_FLAGS
COMMON_CMAKE_C_COMPILER=icc
COMMON_CMAKE_CXX_COMPILER=icpc
## ambient ##
AMBIENT_BOOST_BINDINGS_INCLUDE=/project/h07/TEST_ALPS/include
AMBIENT_SCALAPACK_LIBRARY="-lmkl_scalapack_lp64 -lmkl_blacs_openmpi_lp64"
## dmrg ##
DMRG_BLAS_LAPACK_SELECTOR="mkl_sequential"
DMRG_ALPS_ROOT_DIR=/project/h07/TEST_ALPS
DMRG_USE_AMBIENT=OFF
DMRG_ENABLE_OMP=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
