#!/bin/bash

SITE=eiger
PATH_TRUNK=~/maquis2012/src/

#target directory
TYPES=types
DMRG=dmrg
AMBIENT=ambient

#wrapper 
WRAPPER_INTEL_MPI=iccxe_impi
WRAPPER_MVAPICH2_MPI=iccxe_mvapich2
WRAPPER_OPENMPI_MPI=iccxe_openmpi


delete(){
     for i in ${AMBIENT} ${DMRG} ${TYPES}
     do
         cd ${PATH_TRUNK}${i}
         rm -rf ${SITE}_${WRAPPER}
     done
}

WRAPPER=${WRAPPER_INTEL_MPI}
delete
WRAPPER=${WRAPPER_MVAPICH2_MPI}
delete
WRAPPER=${WRAPPER_OPENMPI_MPI}
delete
