#pragma once

// This configuration emulates 256bit LargeIntegers stored in 32bit integers
#define MAX_NUMBER_OF_BITS_THE_LARGE_INTEGER_OCCUPIES 192U

// Polynomial configuration
#define DEGREE_BOUND_X 11U
#define DEGREE_BOUND_Y 11U

// The size of vectors to be used in inner product
#define ELEMENTS_IN_VECTOR 16384U

////////////////
// Derived symbols
#define MULT_RESULT_DEGREE_BOUND_X (DEGREE_BOUND_X*2-1)
#define MULT_RESULT_DEGREE_BOUND_Y (DEGREE_BOUND_Y*2-1)
// For hardware carry-over
#define SINGLE_LARGE_INTEGER_UINT_COUNT ((MAX_NUMBER_OF_BITS_THE_LARGE_INTEGER_OCCUPIES+32-1)/32)
#define SINGLE_POLYNOMIAL_UINT_COUNT (SINGLE_LARGE_INTEGER_UINT_COUNT*DEGREE_BOUND_X*DEGREE_BOUND_Y)
#define SINGLE_INPUT_VECTOR_UINT_COUNT (SINGLE_POLYNOMIAL_UINT_COUNT*ELEMENTS_IN_VECTOR)
#define SINGLE_MULT_RESULT_POLYNOMIAL_UINT_COUNT (SINGLE_LARGE_INTEGER_UINT_COUNT*MULT_RESULT_DEGREE_BOUND_X*MULT_RESULT_DEGREE_BOUND_Y)
////////////////
