#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=ambient
COMPILER=gcc
COMPILER_VERSION=4.7.3
MYAPPS=/project/h07/dolfim/apps/daint/gcc_4_7_3

export PLASMA_ROOT=$MYAPPS/plasma
export ALPS_ROOT=$MYAPPS/alps
export CRAYPE_LINK_TYPE=dynamic
export CXX=CC.dynamic # CC -dynamic -lz $*
export CC=cc.dynamic  # cc -dynamic -lz $*

if [[ -z "$MAQUIS_ONCE" ]]
then
    export MAQUIS_ONCE=true
    module switch PrgEnv-cray PrgEnv-gnu
    module load gcc/4.7.3
    module load cray-hdf5
    module load cmake
fi

COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_BLAS_LAPACK_SELECTOR="manual"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
