#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
PREFIX=ambient
COMPILER=intel14
COMPILER_VERSION=14.0.1
MYAPPS=$SCRATCH/apps/intel_14_0_1

MAQUIS_INSTALL=$MYAPPS/maquis/$CONFIG_NAME
echo $MAQUIS_INSTALL


if [[ -z "$MAQUIS_ONCE" ]]
then
    export MAQUIS_ONCE=true
    module switch PrgEnv-cray PrgEnv-intel
    module load cmake

    export PLASMA_ROOT=$MYAPPS/plasma
    export ALPS_ROOT=$MYAPPS/alps
    export CRAYPE_LINK_TYPE=dynamic
    export PATH=$ALPS_ROOT/bin:$MYAPPS/hdf5/bin:$MYAPPS/bin:$PATH
    export LD_LIBRARY_PATH=${ALPS_ROOT}/lib:$MYAPPS/hdf5/lib:${LD_LIBRARY_PATH}
    export CXX=CC.dynamic # CC -dynamic -lz -gxx-name=/apps/pilatus/gcc/4.8.2/bin/g++ $*
    export CC=cc.dynamic  # cc -dynamic -lz -gcc-name=/apps/pilatus/gcc/4.8.2/bin/gcc $*
    
    export PATH=${MAQUIS_INSTALL}/bin:${PATH}
fi

COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_MPI_CXX_FOUND=TRUE
COMMON_CMAKE_SYSTEM_NAME="Generic"
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
