#!/bin/bash

#global variables
PATH_SRC=$(PWD)/..
COMPILER_NAME="CLANG"
#some export compiler and boost

export CC=clang
export CXX=clang++
export BOOST_ROOT=/usr/local/include

create_directory(){
    cd ${PATH_SRC}
    mkdir build
}

create_vli(){
    cd ${PATH_SRC}/build
    create_dashboards
    cmake -DVLI_TESTS=ON ..
}

create_dashboards(){
    mkdir Dashboards
    echo "set(PREDEFINED_CTEST_SITE \"`uname -n`\")"                                                         >  ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_BUILD_NAME \"${COMPILER_NAME}\")"                                >> ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_SOURCE_DIRECTORY \"${PATH_SRC}\")"                                  >> ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_BINARY_DIRECTORY \"${PATH_SRC}/build\")" >> ./Dashboards/site.cmake
    cat ../Dashboards/site.cmake >> ./Dashboards/site.cmake
    cp ../Dashboards/cmake_common.cmake ./Dashboards/
}

create_distrib(){
    echo "Start creation VLI"
    create_directory
    create_vli
    echo "End creation VLI"
}

create_distrib
