#!/bin/bash -l 

#global variables
PATH_SRC=${PWD}/..
#some export compiler and boost
export BOOST_ROOT=/apps/eiger/boost_1_46_1/ 

create_directory(){
    cd ${PATH_SRC}
    mkdir build_${COMPILER_NAME}
}

create_vli(){
    cd ${PATH_SRC}/build_${COMPILER_NAME}
    create_dashboards
    cmake -DVLI_TESTS=ON ..
}

create_dashboards(){
    mkdir Dashboards
    echo "set(PREDEFINED_CTEST_SITE \"`uname -n`\")"                    >  ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_BUILD_NAME \"${COMPILER_NAME}\")"        >> ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_SOURCE_DIRECTORY \"${PATH_SRC}\")"       >> ./Dashboards/site.cmake
    echo "set(PREDEFINED_CTEST_BINARY_DIRECTORY \"${PATH_SRC}/build_${COMPILER_NAME}\")" >> ./Dashboards/site.cmake
    cat ../Dashboards/site.cmake >> ./Dashboards/site.cmake
    cp ../Dashboards/cmake_common.cmake ./Dashboards/
}

create_distrib(){
    echo "Start creation VLI"
    create_directory
    create_vli
    echo "End creation VLI"
}

module load cmake
COMPILER_NAME="intel"
module load intel
export CC=icc
export CXX=icpc
create_distrib
COMPILER_NAME="gcc"
export CC=gcc
export CXX=g++
module load gcc
create_distrib
