#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_TYPES="void"
STATE_DMRG="build"
# end of target states #
PREFIX=standard
COMPILER=intel
COMPILER_VERSION=12.1.2
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.7-intel
BOOST=boost
BOOST_VERSION=1.47

export CXX=icpc
export CC=icc
export BOOST_ROOT=/cluster/apps/boost/1_47_0_nompi/x86_64/gcc_4.1.2
export MV2_ENABLE_AFFINITY=0

module load ${COMPILER}/${COMPILER_VERSION}
#module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
#module load ${BOOST}/${BOOST_VERSION}

## common ##
MAQUIS_COMMON_DEFAULT_BLAS_LAPACK=manual
MAQUIS_COMMON_BLAS_LAPACK_MANUAL_INCLUDES=/cluster/apps/intel/composer_xe_2011_sp1.8.273/composer_xe_2011_sp1.8.273/mkl/include
MAQUIS_COMMON_CMAKE_CXX_FLAGS="-Wall -O2 -funroll-loops -std=c++0x -m64 -mkl=parallel"
MAQUIS_COMMON_CPU_FREQ="2.2e9"
## types ##
MAQUIS_TYPES_BUILD_AMBIENT=OFF
MAQUIS_TYPES_ENABLE_PARALLEL=OFF
MAQUIS_TYPES_ENABLE_REGRESSION_FUNCTIONAL=OFF
MAQUIS_TYPES_BOOST_BINDINGS_INCLUDE=/cluster/home/phys/ewartt/alps/include
## dmrg ##
MAQUIS_DMRG_ALPS_ROOT_DIR=/cluster/home/phys/ewartt/alps
MAQUIS_DMRG_BUILD_REGRESSION=OFF 
MAQUIS_DMRG_BUILD_AMBIENT=OFF
MAQUIS_DMRG_USE_AMBIENT=OFF

source $ROOT_DIR/scripts/common/common.sh 
execute $*
