#!/bin/bash -l
STATE="build"
STATE_AMBIENT="build"
STATE_DMRG="build"
# end of target states #
PREFIX=default
COMPILER=intel
COMPILER_VERSION=13
MPI_WRAPPER=open_mpi
MPI_WRAPPER_VERSION=1.4
ALPS_DIR=$HOME/opt/alps-intel

export ALPS_ROOT=${ALPS_DIR}
export PATH=${ALPS_DIR}/bin:${PATH}
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}

module purge
module load goto2 python
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load hdf5
module load cmake

## common ##
# MAQUIS_COMMON_CMAKE_CXX_FLAGS="-Wfatal-errors -openmp -w -O3 -DAMBIENT_OMP -DAMBIENT_CPP11 -DNDEBUG -std=c++11 -L/apps/castor/plasma-2.4.6/lib -I/users/akosenko/maquis2012/src/types/src"
# MAQUIS_COMMON_CMAKE_CXX_FLAGS_RELEASE="-Wfatal-errors -openmp -w -O3 -DAMBIENT_OMP -DAMBIENT_CPP11 -DNDEBUG -std=c++11 -L/apps/castor/plasma-2.4.6/lib -I/users/akosenko/maquis2012/src/types/src"
## dmrg ##
MAQUIS_DMRG_DEFAULT_BLAS_LAPACK=manual
MAQUIS_DMRG_BLAS_LAPACK_MANUAL_LIBS="-mkl"
MAQUIS_DMRG_ENABLE_OMP=ON
MAQUIS_DMRG_BUILD_MULTIGRID=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
