#!/bin/bash -l
STATE="void"
STATE_AMBIENT=""
STATE_DMRG="build"

COMPILER=intel
COMPILER_VERSION=13.1
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.9
ALPS_DIR=$HOME/apps/monch/alps-intel13

export ALPS_ROOT=${ALPS_DIR}
export PATH=${ALPS_DIR}/bin:${PATH}
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}

export CC=icc
export CXX=icpc

module load gcc/4.7.3 hdf5/1.8.11-intel13 intel/13.1.0 mvapich2/1.9-intel13 python cmake

DMRG_BLAS_LAPACK_SELECTOR="mkl_parallel"
DMRG_ENABLE_OMP=ON
DMRG_BUILD_MULTIGRID=ON
DMRG_REGRESSION_PERFORMANCE_TESTS=ON

source $ROOT_DIR/scripts/common/common.sh 

execute $*
