#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=
COMPILER=intel
COMPILER_VERSION=14.0.1
MPI_WRAPPER=impi
MPI_WRAPPER_VERSION=2013

ALPS_DIR=$HOME/apps/monch/alps-intel
MAQUIS_INSTALL=$ROOT_DIR/_installs/monch/_intel_impi
echo $MAQUIS_INSTALL

export ALPS_ROOT=${ALPS_DIR}
export PATH=${ALPS_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${ALPS_DIR}/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}
export CC=icc
export CXX=icpc

module load gcc/4.7.3 hdf5/1.8.11-gcc-4.7.3 python/2.7.5-gcc-4.7.3 intel/14.0.1 cmake

# MAQUIS exports after ALPS
export PATH=${MAQUIS_INSTALL}/bin:${PATH}

COMMON_CMAKE_INSTALL_PREFIX=${MAQUIS_INSTALL}
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"

DMRG_ENABLE_OMP=ON
DMRG_BUILD_AMBIENT=OFF
DMRG_USE_AMBIENT=OFF
DMRG_REGRESSION_PERFORMANCE_TESTS=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
