#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="build"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=13.1.0
MPI_WRAPPER=mvapich2 # not used
MPI_WRAPPER_VERSION=1.9-intel13

export ALPS_ROOT=/users/akosenko/apps/alps/r7223/icc/13.1.0
export PLASMA_ROOT=/apps/castor/plasma-2.4.6
export PATH=${ALPS_ROOT}/bin:${PATH}
export CC=mycc
export CXX=myCC

module load gcc/4.7.3 hdf5/1.8.11-intel13 intel/13.1.0 mvapich2/1.9-intel13 python cmake

COMMON_MPI_CXX_FOUND=TRUE
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
