/*
 * Ambient, License - Version 1.0 - May 3rd, 2012
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef AMBIENT_UTILS_TIMINGS
#define AMBIENT_UTILS_TIMINGS
#include "ambient/ambient.hpp"
#include "ambient/utils/io.hpp"
#include <pthread.h>

#define BILLION 0x3B9ACA00

namespace ambient {

    class timer {
    public:
        timer(std::string name, pthread_t thread): val(0.0), name(name), count(0), thread_(thread){}
        timer(std::string name): val(0.0), name(name), count(0), thread_(pthread_self()){}
       ~timer(){ report(); }
     
        double get_time() const {
            return val;
        }
        void report(){
            std::cout << name << " " << val << ", count : " << count << "\n";
        }
        void begin(){
            pthread_getcpuclockid(this->thread_,&this->cid_);
            struct timespec ts; // from time.h
            clock_gettime(this->cid_, &ts);
            this->t0 = ts.tv_sec+(((double)ts.tv_nsec / (double)(BILLION)));
        }    
        void end(){
            count++;
            struct timespec ts;
            clock_gettime(this->cid_, &ts);
            this->val += (ts.tv_sec+(((double)ts.tv_nsec / (double)(BILLION))) - this->t0);
        }
    private:    
        pthread_t thread_; 
        clockid_t cid_;
        double val, t0;
        unsigned long long count;
        std::string name;
    };
}

#endif

