#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=omp
COMPILER=intel
COMPILER_VERSION=13.0.1

export MKLROOT=/apps/eiger/intel/2013_0_1/mkl
export ALPS_ROOT=/project/h07/TEST_ALPS
export CXX=icpc
export CC=icc

module load ${COMPILER}/${COMPILER_VERSION}
module load cmake

## common ##
COMMON_CMAKE_C_COMPILER=icc
COMMON_CMAKE_CXX_COMPILER=icpc
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"

## dmrg ##
DMRG_ALPS_ROOT_DIR=/project/h07/ALPS_INTEL12_O0
DMRG_ENABLE_OMP=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
