#!/bin/bash -l
STATE="void"
STATE_AMBIENT=""
STATE_DMRG="build"

COMPILER=intel
COMPILER_VERSION=13.1
MPI_WRAPPER=open_mpi
MPI_WRAPPER_VERSION=1.4
ALPS_DIR=$HOME/opt/alps-intel

export ALPS_ROOT=${ALPS_DIR}
export PATH=${ALPS_DIR}/bin:${PATH}
export PYTHONPATH=${ALPS_DIR}/lib:${PYTHONPATH}

module purge
module load goto2 python
module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load hdf5
module load cmake

DMRG_BLAS_LAPACK_SELECTOR="mkl_parallel"
DMRG_ENABLE_OMP=ON
DMRG_BUILD_MULTIGRID=ON
DMRG_REGRESSION_PERFORMANCE_TESTS=ON

source $ROOT_DIR/scripts/common/common.sh 

execute $*
