#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=ambient
COMPILER=intel
COMPILER_VERSION=13.0.1
MPI_WRAPPER=impi
MPI_WRAPPER_VERSION=4.0

export MKLROOT=/apps/eiger/intel/2013_0_1/mkl
export PLASMA_ROOT=/apps/castor/plasma-2.4.6
export ALPS_ROOT=/project/h07/TEST_ALPS
export CXX=mpiicpc
export CC=mpiicc

#export BOOST_ROOT=/apps/eiger/boost_1_46_1

module load gcc/4.7.2
module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
#module load ${BOOST}/${BOOST_VERSION}
module load cmake

source /apps/eiger/Intel-MPI-4.0/intel64/bin/mpivars.sh

## common ##
COMMON_BLAS_LAPACK_SELECTOR="mkl_parallel"
COMMON_PLASMA_LIB_DIR="$PLASMA_ROOT/lib"
DMRG_BUILD_AMBIENT=ON
DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
