#!/bin/bash -l
STATE="void"
STATE_AMBIENT="void"
STATE_DMRG="void"
# end of target states #
SHARED_FS=true
PREFIX=standard
COMPILER=iccxe
COMPILER_VERSION=2011
MPI_WRAPPER=mvapich2
MPI_WRAPPER_VERSION=1.7-intel
BOOST=boost
BOOST_VERSION=1.46.1

export CXX=icpc
export CC=icc
export BOOST_ROOT=/apps/eiger/boost_1_46_1
export MV2_ENABLE_AFFINITY=0

module load ${COMPILER}/${COMPILER_VERSION}
module load ${MPI_WRAPPER}/${MPI_WRAPPER_VERSION}
module load ${BOOST}/${BOOST_VERSION}

## common ##
MAQUIS_COMMON_DEFAULT_BLAS_LAPACK=manual
MAQUIS_COMMON_BLAS_LAPACK_MANUAL_INCLUDES=/apps/todi/intel/composerxe-2011.3.174/mkl/include
MAQUIS_COMMON_CMAKE_CXX_FLAGS="-Wall -O2 -funroll-loops -std=c++0x -m64 -mkl=parallel"
## ambient ##
MAQUIS_AMBIENT_ENABLE_REGRESSION_FUNCTIONAL=ON
MAQUIS_AMBIENT_BOOST_BINDINGS_INCLUDE=/project/h07/ALPS_INTEL_EIGER/include
## dmrg ##
MAQUIS_DMRG_ALPS_ROOT_DIR=/project/h07/ALPS_INTEL_EIGER
MAQUIS_DMRG_BUILD_REGRESSION=ON 
MAQUIS_DMRG_BUILD_AMBIENT=ON 
MAQUIS_DMRG_USE_AMBIENT=ON

source $ROOT_DIR/scripts/common/common.sh 
execute $*
