/*
 * Ambient, License - Version 1.0 - May 3rd, 2012
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef AMBIENT_CONTROLLERS_SSM_CONTROLLER
#define AMBIENT_CONTROLLERS_SSM_CONTROLLER

#define AMBIENT_STACK_RESERVE 65536

namespace ambient { namespace controllers { namespace ssm {

    using ambient::models::ssm::history;
    using ambient::models::ssm::revision;

    class controller {
    public:
        typedef ambient::memory::serial_region<AMBIENT_INSTR_BULK_CHUNK, 
                                               ambient::memory::serial_factory<AMBIENT_INSTR_BULK_CHUNK> 
                                              > memory_type;
        class scope {
        public:
            int rank;
            ambient::locality state;
            virtual bool tunable() const = 0;
            virtual void score(int c, size_t v) const {}
            virtual void select(int c) const {}
            virtual void toss(){}
        };

        controller();
       ~controller();
        void init(int db = 0);
        bool empty();
        void flush();
        void clear();
        bool queue (functor* f);
        bool update(revision& r);
        void sync  (revision* r);
        void lsync (revision* r);
        void rsync (revision* r);
        void lsync (transformable* v);
        void rsync (transformable* v);
        template<typename T> void collect(T* o);
        void squeeze(revision* r) const;

        bool tunable();
        void schedule();
        void intend_read(history* o);
        void intend_write(history* o);

        bool scoped() const;
        void set_context(const scope* s);
        void pop_context();
        bool remote();
        bool local();
        bool common();
        int which();

        void touch(const history* o);
        void use_revision(history* o);
        template<ambient::locality L, typename G>
        void add_revision(history* o, G g);

        void fence() const;
        int  get_rank() const;
        int  get_shared_rank() const;
        int  get_dedicated_rank() const;
        int  get_num_db_procs() const;
        int  get_num_workers() const;
        int  get_num_procs() const;
        int get_sid() const;
        int generate_sid();
        channels::mpi::channel & get_channel();

        void meminfo() const;
        bool verbose() const;

        const scope* context;
        const scope* context_base;
        memory_type memory;
    private:
        models::ssm::model model;
        channels::mpi::channel channel;
        std::vector< functor* > stack_m;
        std::vector< functor* > stack_s;
        std::vector< functor* >* chains;
        std::vector< functor* >* mirror;
        ambient::memory::collector garbage;
        bool serial;
        int sid;
        int db;
    };
    
} } }

namespace ambient {
    controllers::ssm::controller& get_controller();
}

#endif
