
if(ALPS_FOUND)
  set(MAQUIS_Boost_INCLUDE_DIRS ${ALPS_INCLUDE_DIRS})
  if(ALPS_Boost_LIBRARIES)
		set(MAQUIS_Boost_LIBRARIES ${ALPS_Boost_LIBRARIES})
		set(MAQUIS_Boost_UNIT_TEST_FRAMEWORK_LIBRARY "-lboost_unit_test_framework -lboost_test_exec_monitor -lboost_prg_exec_monitor")
	else(ALPS_Boost_LIBRARIES)
		set(MAQUIS_Boost_LIBRARIES boost) # only for back compatibility
	endif(ALPS_Boost_LIBRARIES)
  set(MAQUIS_Boost_LIBRARY_DIRS ${ALPS_LIBRARY_DIRS})
else(ALPS_FOUND)
  set(BOOST_ROOT $ENV{BOOST_ROOT} CACHE PATH "Path to the Boost installation (or to the Boost sources)")
  find_package(Boost 1.43.0 COMPONENTS date_time filesystem program_options python regex system serialization thread)
 if (APPLE AND NOT Boost_FOUND)
    find_package(boost COMPONENTS date_time-mt filesystem-mt program_options-mt python-mt regex-mt system-mt serialization-mt thread-mt)
  endif(APPLE AND NOT Boost_FOUND)
  if(Boost_FOUND)
    set(MAQUIS_Boost_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})  
    set(MAQUIS_Boost_LIBRARIES ${Boost_LIBRARIES})
    set(MAQUIS_Boost_LIBRARY_DIRS ${Boost_LIBRARY_DIRS})
    #include_directories(${Boost_INCLUDE_DIRS})
  endif(Boost_FOUND)
endif(ALPS_FOUND)

